name: resolverscheck
on:
  schedule:
    - cron:  '10 0 * * *'
  workflow_dispatch:

jobs:
  resolverscheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: check
        run: |
          rm -rf *
          sudo apt-get install jq
          git clone https://github.com/dnscrypt/dnscrypt-resolvers.git
          cp .github/workflows/relaycheck.sh dnscrypt-resolvers/.github/workflows/relaycheck.sh
          cd dnscrypt-resolvers
          curl https://download.dnscrypt.info/dnscrypt-resolvers/json/public-resolvers.json | jq -r '.[] | select(.dnssec == true) | select(.ipv6 == false) | select(.nofilter == false) | select(.nolog == true) | select(.proto == "DNSCrypt") | .name,.stamp' public-resolvers.json | sed -e '/family/,+1d' -e '/sfw/,+1d' -e '/nogoogle/,+1d'  -e '/adguard/,+1d' -e '/cleanbrowsing/,+1d' -e '/quad9/,+1d' -e 's/^/## /g' -e 's/## sdns/sdns/g' > public-resolvers.txt > v3/public-resolvers.md
          .github/workflows/resolverscheck.sh | tee resolverscheck
          sort -u resolverscheck | tee ../resolverscheck
          chmod +x .github/workflows/relaycheck.sh
          .github/workflows/relaycheck.sh | tee relaycheck
          sed -e '/linux/d' -e '/ERROR/d' relaycheck > relaycheck.txt
          sort -u relaycheck.txt | tee ../relaycheck
          rm -rf ../dnscrypt-resolvers
      - name: commit
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git add .
          git commit --allow-empty -m "$(git log -1 --pretty=%s)"
          git push
          
